name: FOSS License Scan

on:
  pull_request:
    paths:
      - 'src/**'
      - 'check_license_policy.py'

jobs:
  license-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install ScanCode Toolkit
        run: |
          pip install scancode-toolkit

      - name: Create reports directory
        run: mkdir -p reports

      - name: Run ScanCode Toolkit
        run: |
          scancode -clpeui --processes 1 --json-pp reports/axios-scan.json src/axios

      - name: Run license policy check and capture output
        id: license_check
        shell: bash
        run: |
          summary=$(python3 check_license_policy.py)
          echo "summary<<EOF" >> $GITHUB_OUTPUT
          echo "$summary" >> $GITHUB_OUTPUT
          echo "EOF" >> $G
